import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./(components)/Navbar/Navbar";
import TopNav from "./(components)/topNav/topNav";
import "./globals.css";
import Footer from "./(components)/Footer/footer";
import MaintenancePopup from './Maintenance';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "UpSkill - Learn, Build, and Grow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MaintenancePopup />
        <TopNav showTopNav={true}/>
        <Navbar />
        {children}
        {/* Footer */}
        <Footer/>
      </body>
    </html>
  );
}
